import Head from "next/head"
import QRCode from "qrcode"
import { useState } from "react"

export default function Home() {
  const [text, setText] = useState("")
  const [url, setUrl] = useState("")

  const generateQR = async e => {
    e.preventDefault()
    try {
      const qr = await QRCode.toDataURL(text, {
        errorCorrectionLevel: "H",
        type: "image/jpeg",
        quality: 0.3,
        margin: 1,
        width: 500,
        height: 500,
      })
      setUrl(qr)
    } catch (err) {
      console.error(err)
    }
  }
  return (
    <div className="flex justify-center items-center page bg-gray-100">
      <Head>
        <title>QR-Code Gentator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="rounded bg-white shadow-lg p-4 m-2 md:w-96 w-full">
        <h1 className="text-gray-400 text-xl text-center mb-2 print:hidden">
          QR-Code Gentator
        </h1>

        <form onSubmit={generateQR} className="print:hidden">
          <div className="flex">
            <div className="relative w-full">
              <input
                type="search"
                id="search-dropdown"
                className="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-l-lg border-l-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 "
                placeholder="QrCode Content"
                value={text}
                onChange={e => setText(e.target.value)}
                required
              />
              <button
                type="submit"
                className="absolute top-0 right-0 p-2.5 text-sm font-medium text-white bg-blue-700 rounded-r-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 "
              >
                Generate
              </button>
            </div>
          </div>
        </form>
        <hr className="mt-2 h-px bg-gray-200 border-0"></hr>
        <div className="w-full p-2 flex justify-center mt-2 bg-gray-200">
          {url != "" ? (
            <div className="w-full p-2 text-center">
              <img src={url} className="w-full mb-2" />
              <button onClick={() => window.print()} className="print:hidden text-base bg-slate-800 text-white rounded p-2">Print QR-Code</button>
            </div>
          ) : (
            "Qrcode Here"
          )}
        </div>
        <hr className="mt-2 h-px bg-gray-200 border-0"></hr>
        <div className="footer print:hidden text-base p-2 text-center text-gray-500">copyright © all rights reserved to Ibrahim Hassanin</div>
      </main>
    </div>
  )
}
