import Head from "next/head"

import Navbar from "../components/Navbar"

export default function Home() {

  return (
    <div className="flex justify-center pt-7 page bg-gray-100">
      <Head>
        <title>QR-Code Gentator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="rounded bg-white shadow-lg p-4 m-2 md:w-1/2 w-full">
        <Navbar />
        <div className="text-center mb-2 flex justify-center">
          <img src="/logo.jpg" />
        </div>

        
        <div className="w-full p-2 flex justify-center mt-2 bg-gray-200">
          <div className="text-base" dir="rtl">
            <p>
            الباركود: هو عبارة عن رمز أحادي البعد يتألف من مجموعة من الأرقام والخطوط الطولية المختلفة السماكة، حيث يتم وضعه على المنتجات التجارية والأدوية والسلع، ليقوم البائع بعد ذلك بتمرير هذا الرمز فوق جهاز خاص ليعرف كل البيانات المتعلقة بالسلعة المطلوب شراؤها، فيما يتم قراءة الـ "باركود" عن طريق جهاز خاص يسمى ماسح ضوئي والذى يقوم بإصدار شعاع ضوئي على الشفرة ليقوم بعد ذلك بتحليل الضوء المنعكس وفك ترميز الكود وإرسال البيانات إلى الكمبيوتر المتصل به لعرضها.
            </p>
            <hr className="mt-2 h-px bg-gray-200 border-0"></hr>
            <p>
            QR Code:
هو عبارة عن صورة مكونة من نقاط أو خطوط مرتبة بشكل رقمي، ويتم استخدامها في اختصار المعلومات الخاصة بالكثير من الأشياء الموجودة في حياتنا اليومية، حيث يمكن وصفه بأنه النسخة المطورة أو "الجيل الثاني" من الباركود.
            </p>
            <hr className="mt-2 h-px bg-gray-200 border-0"></hr>
            
          </div>
        </div>
        <hr className="mt-2 h-px bg-gray-200 border-0"></hr>
        <div className="footer print:hidden text-base p-2 text-center text-gray-500">copyright © all rights reserved <br /> Ibrahim Hassanin</div>
      </main>
    </div>
  )
}
